version: '3.4'
services: 
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      POSTGRES_DB:  ps5_news
      POSTGRES_USER: ps5
      POSTGRES_PASSWORD: ps5_123
volumes: 
  postgres_data:
    name: ps5_news_postgres_data
    driver: local