version: '3.4'
services: 
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:  ps5_news
      POSTGRES_USER: ps5
      POSTGRES_PASSWORD: ps5_123
  chrome:
    image: selenium/standalone-chrome
    ports: 
      - "4444:4444"
    volumes: 
      - /dev/shm:/dev/shm
  backend:
    # image: abradat/ps5-news:latest
    build: 
      ./ps5-news
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2
    depends_on: 
      - postgres
      - chrome
    environment: 
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/ps5_news
      DATASOURCE_USERNAME:  ps5
      DATASOURCE_PASSWORD:  ps5_123
      SELENIUM_URL: http://chrome:4444/wd/hub
    command: mvn clean package -DskipTests=true spring-boot:run
volumes: 
  postgres_data:
    name: ps5_news_postgres_data
    driver: local